name: CI

on:
  push:
    branches: ~
  workflow_dispatch: ~

jobs:
  
  ci:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup

      - name: Format and lint
        run: |
          dart format --output=none --set-exit-if-changed . && \
          flutter analyze

      - name: Unit and Widget tests
        run: flutter test test/