name: main

on:
  push:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch: ~

jobs:
  
  test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
          cache: true

      - name: Install
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Unit and Widget tests
        run: flutter test test/

  integration_test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
          cache: true

      - name: Install
        run: flutter pub get

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Integration tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        env:
          BREIZH_BLOK_API_HOST: ${{ secrets.BREIZH_BLOK_API_HOST }}
          BREIZH_BLOK_GMAPS_KEY: ${{ secrets.BREIZH_BLOK_GMAPS_KEY }}
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          # flaky, sometimes timeouts 12 min: https://github.com/flutter/flutter/issues/105913
          script: flutter test integration_test --dart-define="API_HOST=$BREIZH_BLOK_API_HOST" --dart-define="GMAPS_KEY=$BREIZH_BLOK_GMAPS_KEY" --verbose