name: main

on:
  push:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch: ~

jobs:
  
  test:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.3'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Install
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Unit and Widget tests
        run: flutter test test/

      - name: Integration tests
        # flaky, sometimes tests timeouts, or emulator shutdowns unexpectedly
        # continue-on-error: true
        timeout-minutes: 30
        env:
          BREIZH_BLOK_API_HOST: ${{ secrets.BREIZH_BLOK_API_HOST }}
          BREIZH_BLOK_GMAPS_KEY: ${{ secrets.BREIZH_BLOK_GMAPS_KEY }}
        run: |
          flutter emulators --launch ios
          flutter test integration_test --dart-define="API_HOST=$BREIZH_BLOK_API_HOST" --dart-define="GMAPS_KEY=$BREIZH_BLOK_GMAPS_KEY" --verbose --suppress-analytics