name: main

on:
  push:
    branches:
      - 'develop'
      - 'main'
  workflow_dispatch: ~

jobs:
  ci:
    runs-on: macos-11
    timeout-minutes: 60
    strategy:
      matrix:
        device:
          # The available simulators are listed by the "xcrun xctrace list devices" command
          - iPhone 14 Pro Max Simulator (16.4)
      fail-fast: true
    steps:
      - uses: actions/checkout@v3

      - name: "List all simulators"
        run: "xcrun xctrace list devices"

      - name: "Start Simulator"
      
        run: |
          UDID=$(xcrun xctrace list devices | grep -m 1 "^${{ matrix.device }}" | awk '{gsub(/[()]/,""); print $NF}')
          echo $UDID
          open -a Simulator --args -CurrentDeviceUDID "${UDID:?No Simulator with this name found}"

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
          cache: true

      - name: Install
        run: flutter pub get

      - name: Lint
        run: flutter analyze

      - name: Unit and Widget tests
        run: flutter test test/

      - name: Integration tests
        env:
          BREIZH_BLOK_API_HOST: ${{ secrets.BREIZH_BLOK_API_HOST }}
          BREIZH_BLOK_GMAPS_KEY: ${{ secrets.BREIZH_BLOK_GMAPS_KEY }}
        run: flutter test integration_test --dart-define="API_HOST=$BREIZH_BLOK_API_HOST" --dart-define="GMAPS_KEY=$BREIZH_BLOK_GMAPS_KEY"

  android:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'
          cache: true
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          BREIZH_BLOK_API_HOST: ${{ secrets.BREIZH_BLOK_API_HOST }}
          BREIZH_BLOK_GMAPS_KEY: ${{ secrets.BREIZH_BLOK_GMAPS_KEY }}
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test --dart-define="API_HOST=$BREIZH_BLOK_API_HOST" --dart-define="GMAPS_KEY=$BREIZH_BLOK_GMAPS_KEY"